fix: Update atom-package-deps
atom-community/atom-ide-datatip pull request #119
Opened 2021-02-15 17:29 UTC by DeeDeeG

Fixes installing Atom package dependencies when `apm` has a space in its install path.

See: https://github.com/steelbrain/package-deps/pull/331

2021-02-16 04:40 UTC, aminya requested changes
We should put this on hold.

There are issues with the new package-deps:

https://github.com/atom-community/atom-ide-base/pull/60

2021-02-17 11:52 UTC, deankevorkian commented
Hey @DeeDeeG I missed this PR, sorry, accidentally open one [myself](https://github.com/atom-community/atom-ide-datatip/pull/120)
I can close mine if you want to bump it back to 7.2.2 now that it also works on CI, or we can stay with mine

2021-02-17 12:07 UTC, aminya commented
Superceded by #120

2021-02-17 12:07 UTC, closed without merging

2021-02-19 14:18 UTC, DeeDeeG commented
@deankevorkian no worries. Thanks.